ccv_nnc_compat.o : ccv_nnc_compat.cu \
    /usr/include/stdc-predef.h \
    /opt/cuda/bin/..//include/cuda_runtime.h \
    /opt/cuda/bin/..//include/host_config.h \
    /opt/cuda/bin/..//include/crt/host_config.h \
    /usr/include/features.h \
    /usr/include/sys/cdefs.h \
    /usr/include/bits/wordsize.h \
    /usr/include/bits/long-double.h \
    /usr/include/gnu/stubs.h \
    /usr/include/gnu/stubs-64.h \
    /opt/cuda/bin/..//include/builtin_types.h \
    /opt/cuda/bin/..//include/device_types.h \
    /opt/cuda/bin/..//include/host_defines.h \
    /opt/cuda/bin/..//include/crt/host_defines.h \
    /opt/cuda/bin/..//include/driver_types.h \
    /opt/cuda/bin/..//include/vector_types.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include-fixed/limits.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include-fixed/syslimits.h \
    /usr/include/limits.h \
    /usr/include/bits/libc-header-start.h \
    /usr/include/bits/posix1_lim.h \
    /usr/include/bits/local_lim.h \
    /usr/include/linux/limits.h \
    /usr/include/bits/posix2_lim.h \
    /usr/include/bits/xopen_lim.h \
    /usr/include/bits/uio_lim.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/stddef.h \
    /opt/cuda/bin/..//include/surface_types.h \
    /opt/cuda/bin/..//include/texture_types.h \
    /opt/cuda/bin/..//include/library_types.h \
    /opt/cuda/bin/..//include/channel_descriptor.h \
    /opt/cuda/bin/..//include/cuda_runtime_api.h \
    /opt/cuda/bin/..//include/cuda_device_runtime_api.h \
    /opt/cuda/bin/..//include/driver_functions.h \
    /opt/cuda/bin/..//include/vector_functions.h \
    /opt/cuda/bin/..//include/vector_functions.hpp \
    /opt/cuda/bin/..//include/common_functions.h \
    /opt/cuda/bin/..//include/crt/common_functions.h \
    /usr/include/string.h \
    /usr/include/bits/types/locale_t.h \
    /usr/include/bits/types/__locale_t.h \
    /usr/include/strings.h \
    /usr/include/time.h \
    /usr/include/bits/time.h \
    /usr/include/bits/types.h \
    /usr/include/bits/typesizes.h \
    /usr/include/bits/timex.h \
    /usr/include/bits/types/struct_timeval.h \
    /usr/include/bits/types/clock_t.h \
    /usr/include/bits/types/time_t.h \
    /usr/include/bits/types/struct_tm.h \
    /usr/include/bits/types/struct_timespec.h \
    /usr/include/bits/types/clockid_t.h \
    /usr/include/bits/types/timer_t.h \
    /usr/include/bits/types/struct_itimerspec.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/new \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/x86_64-pc-linux-gnu/bits/c++config.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/x86_64-pc-linux-gnu/bits/os_defines.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/x86_64-pc-linux-gnu/bits/cpu_defines.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/exception \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/atomic_lockfree_defines.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/exception_ptr.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/exception_defines.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/nested_exception.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/move.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/concept_check.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/type_traits \
    /usr/include/stdio.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/stdarg.h \
    /usr/include/bits/types/__fpos_t.h \
    /usr/include/bits/types/__mbstate_t.h \
    /usr/include/bits/types/__fpos64_t.h \
    /usr/include/bits/types/__FILE.h \
    /usr/include/bits/types/FILE.h \
    /usr/include/bits/types/struct_FILE.h \
    /usr/include/bits/types/cookie_io_functions_t.h \
    /usr/include/bits/stdio_lim.h \
    /usr/include/bits/sys_errlist.h \
    /usr/include/bits/stdio.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/stdlib.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/cstdlib \
    /usr/include/stdlib.h \
    /usr/include/bits/waitflags.h \
    /usr/include/bits/waitstatus.h \
    /usr/include/bits/floatn.h \
    /usr/include/sys/types.h \
    /usr/include/bits/stdint-intn.h \
    /usr/include/endian.h \
    /usr/include/bits/endian.h \
    /usr/include/bits/byteswap.h \
    /usr/include/bits/uintn-identity.h \
    /usr/include/sys/select.h \
    /usr/include/bits/select.h \
    /usr/include/bits/types/sigset_t.h \
    /usr/include/bits/types/__sigset_t.h \
    /usr/include/bits/pthreadtypes.h \
    /usr/include/bits/thread-shared-types.h \
    /usr/include/bits/pthreadtypes-arch.h \
    /usr/include/alloca.h \
    /usr/include/bits/stdlib-bsearch.h \
    /usr/include/bits/stdlib-float.h \
    /usr/include/assert.h \
    /opt/cuda/bin/..//include/crt/math_functions.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/math.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/cmath \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/cpp_type_traits.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/ext/type_traits.h \
    /usr/include/math.h \
    /usr/include/bits/math-vector.h \
    /usr/include/bits/libm-simd-decl-stubs.h \
    /usr/include/bits/flt-eval-method.h \
    /usr/include/bits/fp-logb.h \
    /usr/include/bits/fp-fast.h \
    /usr/include/bits/mathcalls-helper-functions.h \
    /usr/include/bits/mathcalls.h \
    /usr/include/bits/mathcalls-narrow.h \
    /usr/include/bits/iscanonical.h \
    /usr/include/bits/mathinline.h \
    /opt/cuda/bin/..//include/crt/math_functions.hpp \
    /opt/cuda/bin/..//include/cuda_surface_types.h \
    /opt/cuda/bin/..//include/cuda_texture_types.h \
    /opt/cuda/bin/..//include/device_functions.h \
    /opt/cuda/bin/..//include/crt/device_functions.h \
    /opt/cuda/bin/..//include/crt/device_functions.hpp \
    /opt/cuda/bin/..//include/device_atomic_functions.h \
    /opt/cuda/bin/..//include/device_atomic_functions.hpp \
    /opt/cuda/bin/..//include/crt/device_double_functions.h \
    /opt/cuda/bin/..//include/crt/device_double_functions.hpp \
    /opt/cuda/bin/..//include/sm_20_atomic_functions.h \
    /opt/cuda/bin/..//include/sm_20_atomic_functions.hpp \
    /opt/cuda/bin/..//include/sm_32_atomic_functions.h \
    /opt/cuda/bin/..//include/sm_32_atomic_functions.hpp \
    /opt/cuda/bin/..//include/sm_35_atomic_functions.h \
    /opt/cuda/bin/..//include/sm_60_atomic_functions.h \
    /opt/cuda/bin/..//include/sm_60_atomic_functions.hpp \
    /opt/cuda/bin/..//include/sm_20_intrinsics.h \
    /opt/cuda/bin/..//include/sm_20_intrinsics.hpp \
    /opt/cuda/bin/..//include/sm_30_intrinsics.h \
    /opt/cuda/bin/..//include/sm_30_intrinsics.hpp \
    /opt/cuda/bin/..//include/sm_32_intrinsics.h \
    /opt/cuda/bin/..//include/sm_32_intrinsics.hpp \
    /opt/cuda/bin/..//include/sm_35_intrinsics.h \
    /opt/cuda/bin/..//include/sm_61_intrinsics.h \
    /opt/cuda/bin/..//include/sm_61_intrinsics.hpp \
    /opt/cuda/bin/..//include/crt/sm_70_rt.h \
    /opt/cuda/bin/..//include/crt/sm_70_rt.hpp \
    /opt/cuda/bin/..//include/surface_functions.h \
    /opt/cuda/bin/..//include/texture_fetch_functions.h \
    /opt/cuda/bin/..//include/texture_indirect_functions.h \
    /opt/cuda/bin/..//include/surface_indirect_functions.h \
    /opt/cuda/bin/..//include/device_launch_parameters.h \
    ccv_nnc_compat.h \
    ../ccv_nnc.h \
    ../../ccv.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/float.h \
    /usr/include/sys/param.h \
    /usr/include/signal.h \
    /usr/include/bits/signum.h \
    /usr/include/bits/signum-generic.h \
    /usr/include/bits/types/sig_atomic_t.h \
    /usr/include/bits/types/siginfo_t.h \
    /usr/include/bits/types/__sigval_t.h \
    /usr/include/bits/siginfo-arch.h \
    /usr/include/bits/siginfo-consts.h \
    /usr/include/bits/siginfo-consts-arch.h \
    /usr/include/bits/types/sigval_t.h \
    /usr/include/bits/types/sigevent_t.h \
    /usr/include/bits/sigevent-consts.h \
    /usr/include/bits/sigaction.h \
    /usr/include/bits/sigcontext.h \
    /usr/include/bits/types/stack_t.h \
    /usr/include/sys/ucontext.h \
    /usr/include/bits/sigstack.h \
    /usr/include/bits/ss_flags.h \
    /usr/include/bits/types/struct_sigstack.h \
    /usr/include/bits/sigthread.h \
    /usr/include/bits/param.h \
    /usr/include/linux/param.h \
    /usr/include/asm/param.h \
    /usr/include/asm-generic/param.h \
    ../../nnc/ccv_nnc_tfb.h \
    /usr/include/unistd.h \
    /usr/include/bits/posix_opt.h \
    /usr/include/bits/environments.h \
    /usr/include/bits/confname.h \
    /usr/include/bits/getopt_posix.h \
    /usr/include/bits/getopt_core.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/stdint.h \
    /usr/include/stdint.h \
    /usr/include/bits/wchar.h \
    /usr/include/bits/stdint-uintn.h \
    ../cmd/ccv_nnc_cmd.h \
    ../cmd/ccv_nnc_backend.h \
    ../_ccv_nnc_stream.h \
    /usr/include/ucontext.h \
    /usr/include/bits/indirect-return.h \
    /usr/include/pthread.h \
    /usr/include/sched.h \
    /usr/include/bits/sched.h \
    /usr/include/bits/types/struct_sched_param.h \
    /usr/include/bits/cpu-set.h \
    /usr/include/bits/setjmp.h \
    /opt/cuda/bin/..//include/cuda.h \
    /opt/cuda/bin/..//include/cublas_v2.h \
    /opt/cuda/bin/..//include/cublas_api.h \
    /opt/cuda/bin/..//include/cuComplex.h \
    /opt/cuda/bin/..//include/cuda_fp16.h \
    /opt/cuda/bin/..//include/cuda_fp16.hpp \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/utility \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/stl_relops.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/bits/stl_pair.h \
    /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/initializer_list \
    /opt/cuda/bin/..//include/cudnn.h \
    ../../nnc/ccv_nnc_easy.h \
    ../../nnc/ccv_nnc.h \
    ../../nnc/cmd/ccv_nnc_cmd_easy.h \
    ../../nnc/_ccv_nnc_stream.h
